### ISSUE TITLE
Game crashes when starting to break block with weapon that has the Double attack modifier on it

### ISSUE THREAD

**Issue by Chirqn** [gjhihihi/Tinkers-Innovation#1]
Any left clicking on a block crashes the game while using an item with double attack on it. Crash logs below;

[crash-2024-07-22_07.40.33-client.txt](https://github.com/user-attachments/files/16332321/crash-2024-07-22_07.40.33-client.txt)

**Comment by Chirqn** [comment]
Ah, forgot to add that this is on the 1.18.2 version of tinkersinnovation

**Comment by gjhihihi** [comment]
Processed.
已处理。

**Comment by gjhihihi** [comment]
But it has not had a new version in 1.18

**Comment by gjhihihi** [comment]
A 1.18.2 version that solve the bug has been released.
